name: 'the_bulwark'
profile: 'the_bulwark'
version: '1.0.0'
config-version: 2
dbt-cloud:
    project-id: 70471823552522

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  the_bulwark:
    marts:
        core:
          +materialized: table
          +enabled: true
          reports:
            +schema: reports
    staging:
      +materialized: view
      other:
        +enabled: false

tests:
    the_bulwark:
      +store_failures: false
      +schema: dbt_test_failures

snapshots:
  the_bulwark:
    +schema: snapshots